### ISSUE TITLE
Is mesh-networking always a fully-connected broadcast mesh topology?

### ISSUE THREAD

**Issue by hoyeunglee** [pirate/mesh-networking#13]
is this mesh networking always fully mesh?

**Comment by pirate** [comment]
You mean is it always a broadcast network where everyone receives every packet?  For `UDPLink` yes, it defaults to broadcast mode, but you can build a custom network protocol on top of `mesh-networking` that supports other schemes besides fully connected meshes.

**Comment by hoyeunglee** [comment]
I mean the term used by Cisco , whether each node has all path to other nodes

**Comment by pirate** [comment]
You can set it up however you want.

If you connect every `Node` to the same `Link`, then it's like a fully-connected mesh because it's like plugging everyone in to the same LAN.

If you connect everyone to different `Link`s with `Routers` and custom forwarding rules though (see [examples/large_network.py](https://github.com/pirate/mesh-networking/blob/master/examples/large_network.py), you can design any kind of topology you want, which is the point of the library.

**Comment by hoyeunglee** [comment]
what is the result of small networking example?

i run it , it did not display end just start

and can mesh networking deploy to real network situations instead of simulated in local machine?

![image](https://user-images.githubusercontent.com/5094741/40706476-8742946a-6420-11e8-8714-f1a8c70788a1.png)

**Comment by pirate** [comment]
Did you try typing things in and pressing enter?

I don't officially support Windows, so you're on your own if you want to use Windows.  It's built for Mac/Linux.

Yes it supports building real mesh networks across physical links, see the `examples/lan_chat.py`.
